version: '3.7'

services:
  node-server:
    build:
      dockerfile: Dockerfile.prod
      target: production
    command: node dist/index.js

  db:
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db_queries/init.sql:/docker-entrypoint-initdb.d/init.sql
